import { defineCollection, reference } from "astro:content";
import { glob } from "astro/loaders";
import { z } from "astro/zod";
import { checkHarmony, isNeutral } from "./lib/color";
import {
  CATEGORIES,
  COLOR_MODES,
  COLOR_HARMONIES,
  COLOR_ROLES,
  COLOR_STRATEGIES,
  COLOR_TEMPERATURES,
  ENTRY_TYPES,
  IMAGERY_STYLES,
  IMAGERY_TREATMENTS,
  MOTION_TYPES,
  PERSONALITY_TAGS,
  RATIONALE_BASES,
  SCREEN_TYPES,
  TEXTURES,
  TYPE_ROLES,
  TYPE_STYLES,
} from "./data/taxonomies";

/** A product, e.g. Jira. One product can have several entries (landing, iOS, desktop). */
const products = defineCollection({
  loader: glob({ pattern: "*.yaml", base: "./src/content/products" }),
  schema: z.object({
    name: z.string(),
    website: z.url(),
    category: z.enum(CATEGORIES),
  }),
});

const hex = z
  .string()
  .regex(/^#[0-9A-F]{6}$/, "Use uppercase 6-digit hex, e.g. #0061EF");

const mediaItem = z.object({
  /** File name inside public/media/<entry-id>/ */
  src: z.string(),
  kind: z.enum(["image", "video"]).default("image"),
  alt: z.string().min(1),
  caption: z.string().optional(),
  /** Glossary terms this example shows (imagery and motion examples need at least one). */
  terms: z.array(z.string()).default([]),
});

const source = z.object({
  title: z.string(),
  url: z.url(),
});

/**
 * Shared by every breakdown section: what is used, why we think it is used,
 * where that "why" comes from, and visual examples.
 */
function section<T extends z.ZodRawShape>(
  shape: T,
  { examplesRequired }: { examplesRequired: boolean },
) {
  return z
    .object({
      ...shape,
      what: z.string().min(1),
      why: z.string().min(1),
      basis: z.enum(RATIONALE_BASES),
      sources: z.array(source).default([]),
      examples: examplesRequired
        ? z.array(mediaItem).min(1)
        : z.array(mediaItem).default([]),
    })
    .refine(
      (s) => {
        // Generic shape hides these fields from TypeScript; they always exist.
        const { basis, sources } = s as { basis: string; sources: unknown[] };
        return basis === "interpretation" || sources.length > 0;
      },
      {
        path: ["sources"],
        message: "Brand guidelines / statements need at least one source link.",
      },
    );
}

/** One source of inspiration: a landing page, or screens from an iOS / desktop app. */
const entries = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/entries" }),
  schema: z
    .object({
      product: reference("products"),
      type: z.enum(ENTRY_TYPES),
      sourceUrl: z.url(),
      capturedAt: z.coerce.date(),
      /** Thumbnail used on cards (file name inside public/media/<entry-id>/). */
      cover: z.string(),
      /** The full screenshot(s) or recording(s). The first one leads the detail page. */
      media: z.array(mediaItem).min(1),
      /** Required for iOS / desktop, not used for landing pages. */
      screens: z.array(z.enum(SCREEN_TYPES)).default([]),
      tags: z.array(z.enum(PERSONALITY_TAGS)).min(1),

      /** The palette itself is the example; extra images are optional. */
      colors: section(
        {
          palette: z
            .array(
              z.object({
                hex,
                name: z.string().optional(),
                role: z.enum(COLOR_ROLES),
              }),
            )
            .min(1),
          /** How the main hues relate on the colour wheel. */
          harmony: z.enum(COLOR_HARMONIES),
          /** The palette hexes that form the harmony (shown on the wheel). */
          harmonyColors: z.array(hex).min(1),
          /** How much of each colour is used. */
          strategy: z.enum(COLOR_STRATEGIES),
          mode: z.enum(COLOR_MODES),
          temperature: z.enum(COLOR_TEMPERATURES),
        },
        { examplesRequired: false },
      ),

      /**
       * Each font is shown as a type specimen: rendered live when it's a free
       * web font (`webFont`), otherwise as an image generated by
       * `scripts/type-specimen.mjs` (`specimen`).
       */
      typography: section(
        {
          fonts: z
            .array(
              z
                .object({
                  family: z.string(),
                  style: z.enum(TYPE_STYLES),
                  roles: z.array(z.enum(TYPE_ROLES)).min(1),
                  /** e.g. "Custom", "Licensed (Colophon)", "Google Fonts" */
                  source: z.string().optional(),
                  /** Weights used on the page, lightest first. */
                  weights: z
                    .array(z.object({ value: z.number(), name: z.string() }))
                    .min(1),
                  /** How the page uses the font, largest first. Sizes in px. */
                  scale: z
                    .array(
                      z.object({
                        label: z.string(),
                        size: z.number(),
                        lineHeight: z.number(),
                        weight: z.number(),
                        tracking: z.number().optional(),
                        sample: z.string(),
                      }),
                    )
                    .default([]),
                  /** Specimen image file inside public/media/<entry-id>/. */
                  specimen: z.string().optional(),
                  /** Free web font the site can load to render the specimen live. */
                  webFont: z
                    .object({
                      provider: z.enum(["google"]),
                      family: z.string(),
                    })
                    .optional(),
                })
                .refine((f) => f.specimen || f.webFont, {
                  message:
                    "Add a `specimen` image (custom fonts) or a `webFont` (free fonts).",
                }),
            )
            .min(1),
        },
        { examplesRequired: false },
      ),

      imagery: section(
        {
          styles: z.array(z.enum(IMAGERY_STYLES)).min(1),
          treatments: z.array(z.enum(IMAGERY_TREATMENTS)).default([]),
          textures: z.array(z.enum(TEXTURES)).default([]),
        },
        { examplesRequired: true },
      ),

      /** Only when motion is a notable part of the experience. */
      motion: section(
        { types: z.array(z.enum(MOTION_TYPES)).min(1) },
        { examplesRequired: true },
      ).optional(),
    })
    .superRefine((entry, ctx) => {
      if (entry.type === "landing" && entry.screens.length > 0) {
        ctx.addIssue({
          code: "custom",
          path: ["screens"],
          message: "Landing pages don't use screen types; remove `screens`.",
        });
      }
      if (entry.type !== "landing" && entry.screens.length === 0) {
        ctx.addIssue({
          code: "custom",
          path: ["screens"],
          message: "iOS / desktop entries need at least one screen type.",
        });
      }

      // The stated harmony must match the actual hues.
      const paletteHexes = entry.colors.palette.map((c) => c.hex);
      for (const hexValue of entry.colors.harmonyColors) {
        if (!paletteHexes.includes(hexValue)) {
          ctx.addIssue({
            code: "custom",
            path: ["colors", "harmonyColors"],
            message: `${hexValue} isn't in the palette.`,
          });
        } else if (isNeutral(hexValue)) {
          ctx.addIssue({
            code: "custom",
            path: ["colors", "harmonyColors"],
            message: `${hexValue} is a neutral and has no place on the colour wheel.`,
          });
        }
      }
      const harmonyProblem = checkHarmony(
        entry.colors.harmony,
        entry.colors.harmonyColors,
      );
      if (harmonyProblem) {
        ctx.addIssue({
          code: "custom",
          path: ["colors", "harmony"],
          message: harmonyProblem,
        });
      }

      // Every named style / technique must be shown by at least one example,
      // and every example must name what it shows.
      const { imagery, motion } = entry;
      const checks = [
        {
          key: "imagery",
          claimed: [
            ...imagery.styles,
            ...imagery.treatments,
            ...imagery.textures.filter((t) => t !== "flat-colour"),
          ],
          examples: imagery.examples,
        },
        ...(motion
          ? [
              {
                key: "motion",
                claimed: motion.types,
                examples: motion.examples,
              },
            ]
          : []),
      ];
      for (const { key, claimed, examples } of checks) {
        examples.forEach((example, i) => {
          if (example.terms.length === 0) {
            ctx.addIssue({
              code: "custom",
              path: [key, "examples", i, "terms"],
              message: "Name what this example shows (glossary terms).",
            });
          }
          for (const term of example.terms) {
            if (!(claimed as string[]).includes(term)) {
              ctx.addIssue({
                code: "custom",
                path: [key, "examples", i, "terms"],
                message: `"${term}" isn't listed in this ${key} section.`,
              });
            }
          }
        });
        const shown = new Set(examples.flatMap((e) => e.terms));
        for (const term of claimed) {
          if (!shown.has(term)) {
            ctx.addIssue({
              code: "custom",
              path: [key],
              message: `"${term}" has no example showing it.`,
            });
          }
        }
      }
    }),
});

export const collections = { products, entries };
