import { defineCollection, reference } from "astro:content";
import { glob } from "astro/loaders";
import { z } from "astro/zod";
import {
  CATEGORIES,
  COLOR_MODES,
  COLOR_ROLES,
  COLOR_TEMPERATURES,
  ENTRY_TYPES,
  IMAGERY_STYLES,
  MOTION_TYPES,
  PERSONALITY_TAGS,
  RATIONALE_BASES,
  SCREEN_TYPES,
  TYPE_CLASSIFICATIONS,
  TYPE_ROLES,
} from "./data/taxonomies";

/** A product, e.g. Jira. One product can have several entries (landing, iOS, desktop). */
const products = defineCollection({
  loader: glob({ pattern: "*.yaml", base: "./src/content/products" }),
  schema: z.object({
    name: z.string(),
    website: z.url(),
    category: z.enum(CATEGORIES),
  }),
});

const hex = z
  .string()
  .regex(/^#[0-9A-F]{6}$/, "Use uppercase 6-digit hex, e.g. #0061EF");

const mediaItem = z.object({
  /** File name inside public/media/<entry-id>/ */
  src: z.string(),
  kind: z.enum(["image", "video"]).default("image"),
  alt: z.string().min(1),
  caption: z.string().optional(),
});

const source = z.object({
  title: z.string(),
  url: z.url(),
});

/**
 * Shared by every breakdown section: what is used, why we think it is used,
 * where that "why" comes from, and visual examples.
 */
function section<T extends z.ZodRawShape>(
  shape: T,
  { examplesRequired }: { examplesRequired: boolean },
) {
  return z
    .object({
      ...shape,
      what: z.string().min(1),
      why: z.string().min(1),
      basis: z.enum(RATIONALE_BASES),
      sources: z.array(source).default([]),
      examples: examplesRequired
        ? z.array(mediaItem).min(1)
        : z.array(mediaItem).default([]),
    })
    .refine(
      (s) => {
        // Generic shape hides these fields from TypeScript; they always exist.
        const { basis, sources } = s as { basis: string; sources: unknown[] };
        return basis === "interpretation" || sources.length > 0;
      },
      {
        path: ["sources"],
        message: "Brand guidelines / statements need at least one source link.",
      },
    );
}

/** One source of inspiration: a landing page, or screens from an iOS / desktop app. */
const entries = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/entries" }),
  schema: z
    .object({
      product: reference("products"),
      type: z.enum(ENTRY_TYPES),
      sourceUrl: z.url(),
      capturedAt: z.coerce.date(),
      /** Thumbnail used on cards (file name inside public/media/<entry-id>/). */
      cover: z.string(),
      /** The full screenshot(s) or recording(s). The first one leads the detail page. */
      media: z.array(mediaItem).min(1),
      /** Required for iOS / desktop, not used for landing pages. */
      screens: z.array(z.enum(SCREEN_TYPES)).default([]),
      tags: z.array(z.enum(PERSONALITY_TAGS)).min(1),

      /** The palette itself is the example; extra images are optional. */
      colors: section(
        {
          palette: z
            .array(
              z.object({
                hex,
                name: z.string().optional(),
                role: z.enum(COLOR_ROLES),
              }),
            )
            .min(1),
          mode: z.enum(COLOR_MODES),
          temperature: z.enum(COLOR_TEMPERATURES),
        },
        { examplesRequired: false },
      ),

      /**
       * Each font is shown as a type specimen: rendered live when it's a free
       * web font (`webFont`), otherwise as an image generated by
       * `scripts/type-specimen.mjs` (`specimen`).
       */
      typography: section(
        {
          fonts: z
            .array(
              z
                .object({
                  family: z.string(),
                  classification: z.enum(TYPE_CLASSIFICATIONS),
                  roles: z.array(z.enum(TYPE_ROLES)).min(1),
                  /** e.g. "Custom", "Licensed (Colophon)", "Google Fonts" */
                  source: z.string().optional(),
                  /** Weights used on the page, lightest first. */
                  weights: z
                    .array(z.object({ value: z.number(), name: z.string() }))
                    .min(1),
                  /** How the page uses the font, largest first. Sizes in px. */
                  scale: z
                    .array(
                      z.object({
                        label: z.string(),
                        size: z.number(),
                        lineHeight: z.number(),
                        weight: z.number(),
                        tracking: z.number().optional(),
                        sample: z.string(),
                      }),
                    )
                    .default([]),
                  /** Specimen image file inside public/media/<entry-id>/. */
                  specimen: z.string().optional(),
                  /** Free web font the site can load to render the specimen live. */
                  webFont: z
                    .object({
                      provider: z.enum(["google"]),
                      family: z.string(),
                    })
                    .optional(),
                })
                .refine((f) => f.specimen || f.webFont, {
                  message:
                    "Add a `specimen` image (custom fonts) or a `webFont` (free fonts).",
                }),
            )
            .min(1),
        },
        { examplesRequired: false },
      ),

      imagery: section(
        { styles: z.array(z.enum(IMAGERY_STYLES)).min(1) },
        { examplesRequired: true },
      ),

      /** Only when motion is a notable part of the experience. */
      motion: section(
        { types: z.array(z.enum(MOTION_TYPES)).min(1) },
        { examplesRequired: true },
      ).optional(),
    })
    .superRefine((entry, ctx) => {
      if (entry.type === "landing" && entry.screens.length > 0) {
        ctx.addIssue({
          code: "custom",
          path: ["screens"],
          message: "Landing pages don't use screen types; remove `screens`.",
        });
      }
      if (entry.type !== "landing" && entry.screens.length === 0) {
        ctx.addIssue({
          code: "custom",
          path: ["screens"],
          message: "iOS / desktop entries need at least one screen type.",
        });
      }
    }),
});

export const collections = { products, entries };
